# Generated by Django 4.2.14 on 2024-07-16 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=10, unique=True)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('BUS', 'Bus'), ('TRAM', 'Tram'), ('SUBWAY', 'Subway')], max_length=6)),
                ('capacity', models.PositiveIntegerField()),
                ('last_maintenance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_unittest_project.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_unittest_project.vehicle')),
            ],
            options={
                'unique_together': {('vehicle', 'start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='route',
            name='vehicles',
            field=models.ManyToManyField(through='django_unittest_project.RouteAssignment', to='django_unittest_project.vehicle'),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_unittest_project.vehicle')),
            ],
        ),
    ]
